export const SET_USER = "SET_USER";
export const UPDATE_USERID = "UPDATE_USERID";

export const UPDATE_ROOMMATCH = "UPDATE_ROOMMATCH";
export const UPDATE_PARTNERID = "UPDATE_PARTNERID";
export const UPDATE_TEXTSENDING = "UPDATE_TEXTSENDING";

export const RESET_STATE = "RESET_STATE";
